services:
  - type: web
    name: bibliosena
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd BILIOSENA && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true

